# Generated by Django 4.0 on 2021-12-20 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproject',
            name='mainProject',
        ),
    ]
