# Generated by Django 4.0 on 2021-12-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0002_remove_subproject_mainproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='mainProjectnum',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
